### ISSUE TITLE
Add a "blacklist" regex pattern for git SHA search

### ISSUE THREAD

**Issue by jwu910** [drewbrokke/jack-cli#25]
User should be able to add a custom list of patterns to skip/avoid when navigating the git log.

**Comment by drewbrokke** [comment]
This feature will be added in the next release. 

Commit hashes: 
3db00b7a827c06eb602b47bc942266ad419d6a26
b1f724a272fb0835cbca32af28835646f21b4089

**Comment by drewbrokke** [comment]
@jwu910 the new version of `jack-cli` has been released and contains this feature. See https://www.npmjs.com/package/jack-cli#blacklistpatterns for details.

Please run `npm i -g jack-cli` to update.
