### ISSUE TITLE
Awesome tool

### ISSUE THREAD

**Issue by BarbzYHOOL** [drewbrokke/jack-cli#26]
This is awesome just for git show.

What other good tricks can we do with jack?

**Comment by BarbzYHOOL** [comment]
Just had an idea, we should be able to "checkout" on a commit

**Comment by drewbrokke** [comment]
Hey @BarbzYHOOL!  Thank you so much for your feedback!  I'm glad you like it.  

I think my favorite feature of `jack` is "custom commands".  You can wire up any shell command to be called with a keypress.  `jack` reads a configuration file from your home directory (`~/.jack.json`) and will register any custom command you want as a keypress.

Here's the documentation for it: https://github.com/drewbrokke/jack-cli#custom-key-commands

So for your idea of "checkout", you would simply add an object to the "commands" array in that file that looks like this:

```json
{
	"commandArray": ["git", "checkout", "[%SHA_SINGLE%]"],
	"description": "Check out commit",
	"key": "S-c"
},
```

I'm also working to improve jack so that you can instead just pass a string for the command:

```json
{
	"command": "git checkout [%SHA_SINGLE%]",
	"description": "Check out at commit",
	"key": "S-c"
},
```

That change is not published just yet, but it will be soon.

Please let me know if this is helpful, or if you need any more clarification :)

**Comment by drewbrokke** [comment]
For reference, here is my personal `.jack.json` config file.  I hooked it up to some custom scripts as well.

```json
{
	"commands": [
		{
			"command": "git checkout [%SHA_SINGLE%]",
			"description": "Check out commit",
			"foreground": false,
			"key": "S-z"
		},
		{
			"command": "git -p dsf [%SHA_RANGE%] --patch --stat-width=1000 --ignore-all-space",
			"description": "View total diff (custom)",
			"foreground": true,
			"key": "d"
		},
		{
			"command": "git -p diff [%SHA_RANGE%] --name-only | sed 's,/src/.*,,' | sed 's,/build.gradle,,' | sed 's,/bnd.bnd,,' | sed 's,/.lfrbuild-portal,,' | uniq -c | sort -r | less",
			"commandArray": ["hello", "array"],
			"description": "View changed modules",
			"foreground": true,
			"key": "S-m"
		},
		{
			"command": "ji [%COMMIT_MESSAGE%]",
			"description": "Open Jira ticket in browser",
			"key": "i"
		},
		{
			"command": "getpr [%COMMIT_MESSAGE%]",
			"description": "Open Github PR in browser",
			"key": "p"
		},
		{
			"command": "git format-patch -o /Users/drewb/Desktop/patches [%SHA_SINGLE_OR_RANGE%]",
			"description": "Export commits as patch files",
			"key": "S-p"
		},
		{
			"command": "git revert [%SHA_SINGLE_OR_RANGE%]",
			"description": "Revert commit",
			"key": "S-r",
			"onErrorCommand": "git cherry-pick --abort",
			"refreshOnComplete": true
		},
		{
			"command": "git commit --fixup=[%SHA_SINGLE%]",
			"description": "Fix up commit with index.",
			"foreground": true,
			"key": "S-f",
			"refreshOnComplete": true
		},
		{
			"command": "git rebase -i --autosquash [%SHA_SINGLE%]^",
			"description": "Perform interactive rebase",
			"foreground": true,
			"key": "S-i",
			"onErrorCommand": "git rebase --abort",
			"refreshOnComplete": true
		},
		{
			"command": "filterJack [%COMMIT_MESSAGE%]",
			"description": "Filter the list down to the selected ticket number",
			"foreground": true,
			"key": "S-t"
		},
		{
			"command": "gitk [%SHA_SINGLE_OR_RANGE%]",
			"description": "Open gitk",
			"foreground": false,
			"key": "w"
		}
	],
	"gitShowOptions": "--patch-with-stat --stat-width 1000 --color --ignore-all-space",
	"notificationTimeout": 8000
}
```

**Comment by BarbzYHOOL** [comment]
You should put those examples in the readme or in a file!

So I tried the checkout command:

```
│ error: pathspec '[%SHA_SINGLE%]' did not match any file(s) known to git. │

```


Also if we have a `},` as the last command block, it will not work

**Comment by drewbrokke** [comment]
Hmm, can you paste a copy of your `.jack.json` file?  `jack` should replace those tokens with the actual commit hash.

**Comment by drewbrokke** [comment]
> Also if we have a }, as the last command block, it will not work

You're correct, the `.jack.json` file should be valid JSON :)  I wasn't too careful just pasting a small section of the larger file.

**Comment by BarbzYHOOL** [comment]
```
{
	"commands":[
		{
			"commandArray": ["git", "checkout", "[%SHA_SINGLE%]"],
			"description": "Check out commit",
			"key": "S-c"
		}

	],
	"notificationTimeout":5000
}

```

**Comment by drewbrokke** [comment]
Ah, that was my mistake - I accidentally pushed documentation for the new syntax but have not released it yet. The current token should be "[% SHA_SINGLE %]".  My apologies.

Your new `.jack.json` file will look like this: 
```json
{
	"commands":[
		{
			"commandArray": ["git", "checkout", "[% SHA_SINGLE %]"],
			"description": "Check out commit",
			"key": "S-c"
		}

	],
	"notificationTimeout":5000
}
```

**Comment by BarbzYHOOL** [comment]
Ok it works and damn, the tool is really good in terms of "UI design", maybe you're a UI designer lol

And what is this command: "getpr [%COMMIT_MESSAGE%]" ??

Also in the README.md example you could add 'jack --oneline'

**Comment by drewbrokke** [comment]
> Ok it works and damn, the tool is really good in terms of "UI design", maybe you're a UI designer lol

Haha, thank you 😄 

> And what is this command: "getpr [%COMMIT_MESSAGE%]" ??

'getpr' is one of my personal scripts I wrote to open the latest Gitub Pull Request based on a JIRA ticket number in a commit message.  It's very unique to my work (useful to those in my company), but it's a good example of the power of `jack` - you can easily wire it up to your own personal custom stuff.  If your script takes git commit information, it can be used with `jack` :)

> Also in the README.md example you could add 'jack --oneline'

I'll happily accept pull requests! 😉

**Comment by BarbzYHOOL** [comment]
Ok, for now i'll use it to git show and git checkout, if i get better with git I might have more uses!

Thank you for this and I think more people should discover this tool.

**Comment by drewbrokke** [comment]
Of course! I'm happy you're enjoying it.  Please spread the word!
