### ISSUE TITLE
Alt hotkey?

### ISSUE THREAD

**Issue by BarbzYHOOL** [drewbrokke/jack-cli#27]
We can't use "alt" for custom commands, it's on purpose? why?

**Comment by drewbrokke** [comment]
Hey @BarbzYHOOL, the library I'm using to render the terminal ([blessed](https://github.com/chjj/blessed)) does not currently support the 'alt' or 'option' key.  Only control, meta, and shift are supported.

**Comment by BarbzYHOOL** [comment]
metal? means normal key?

**Comment by drewbrokke** [comment]
Sorry, typo.  Fixed it - it's supposed to say "meta", like "command" on Mac or "windows" on Windows
