### ISSUE TITLE
Next Page and Previous Page hotkeys

### ISSUE THREAD

**Issue by BarbzYHOOL** [drewbrokke/jack-cli#28]
I'm used to scroll in the log with Pg. Up and Pg. Down but in Jack we can only use the arrows.

Could you add Page Up and Page Down?

**Comment by drewbrokke** [comment]
Hey @BarbzYHOOL, PageUp and PageDown should be supported: https://github.com/drewbrokke/jack-cli/blob/master/src/interface/list-view.ts#L57-L63.  Is it not working for you?

**Comment by BarbzYHOOL** [comment]
@drewbrokke It's working in the git log, but not in the git diff (i had not tested in the git log menu though).
And the git diff is usually very very long :P

**Comment by drewbrokke** [comment]
Ah, got it.  It's coming in the next release :)  In the meantime you can use `ctrl-f` and `ctrl-b` in the git diff to page up and down.

**Comment by BarbzYHOOL** [comment]
I tested the latest package (i tried to upgrade with npm i -g jack-cli and npm update jack-cli) but it still doesn't work @drewbrokke 

I'm not even sure I have the latest pkg xD

**Comment by drewbrokke** [comment]
Sorry, it's not released on npm yet.  If you download and build you can try it out right away.

**Comment by BarbzYHOOL** [comment]
:'( dunno how to do that and i'd prefer not, ok anyway you'll close these issues when it's released so i'll get notif :(

**Comment by drewbrokke** [comment]
@BarbzYHOOL the new version of `jack-cli` has been released (1.0.0). It contains this feature.

Please run `npm i -g jack-cli` to update. Thanks!
