### ISSUE TITLE
If I want to install for several users

### ISSUE THREAD

**Issue by BarbzYHOOL** [drewbrokke/jack-cli#29]
Installing it for several users and even root

I'd install it with `npm i -g`

But then, i'd be forced to edit the .jack.json of each user?

**Comment by drewbrokke** [comment]
Hey @BarbzYHOOL, the configuration file is stored in each user's home folder, not in the installed `jack-cli` library.  So in theory each user that logs in should have their own configuration file.  Am I missing something?  Are you instead referring to shell logins?

**Comment by BarbzYHOOL** [comment]
No, you got it right and yes system user. So if I happen to switch to root (yeah maybe bad habit), I won't have the config. There could be a global config

**Comment by drewbrokke** [comment]
This feature will be available in the next release.

Commit hashes:
6885fbe
89fc056

**Comment by BarbzYHOOL** [comment]
Ok, but not sure how to quickly test it

I mean, what should I put in the conf to test? sorry didn't touch jack conf for a long time.

**Comment by drewbrokke** [comment]
@BarbzYHOOL the new version of jack-cli has been released (1.0.0). It contains this feature.

See https://www.npmjs.com/package/jack-cli#jack_cli_config_file_path for more information on this feature.

Please run npm i -g jack-cli to update. Thanks!
