### ISSUE TITLE
up/down arrow keys on the commit view behave differently than expected

### ISSUE THREAD

**Issue by bryceosterhaus** [drewbrokke/jack-cli#3]
When looking at the changes of a commit, it would be useful if the up/down keys would move the diff up and down, rather than switch commit.

Not sure if this is something you intend for users to be able to do, I keep finding myself thinking it will navigate down in the commit diff, rather than a new commit entirely.

**Comment by drewbrokke** [comment]
Good call.  I'll try to use the built-in blessed options.

**Comment by drewbrokke** [comment]
Merged keyboard navigation updates.  Thanks @bryceosterhaus!
