### ISSUE TITLE
Separate out the SHA_RANGE into SHA1 and SHA2

### ISSUE THREAD

**Issue by drewbrokke** [drewbrokke/jack-cli#30]
SHA_RANGE is too opinionated (it evaluates to SHA1^...SHA2) and is not guaranteed to work in all cases.  Providing 2 SHA variables allows for more flexibility on the part of the user for their custom scripts.

SHA1 will always be the ancestor
SHA2 will be the child if there is a marked SHA, or the same as SHA1

**Comment by BarbzYHOOL** [comment]
if u say so

:P

**Comment by drewbrokke** [comment]
I'm gonna keep `SHA_RANGE` around for now but still add these new tokens.

**Comment by drewbrokke** [comment]
I'm gonna close this one as a won't fix for now. It's not as straightforward as I'd hoped, so I'll revisit it in a future release.
