### ISSUE TITLE
Search (ctrl+f like)??

### ISSUE THREAD

**Issue by BarbzYHOOL** [drewbrokke/jack-cli#35]
Sorry, I haven't read your answer on other issues yet, I'm in a hurry so I post quickly :P

There is a typo in the help "Navgate" instead of "Navigate"

But also there is no way to do a search based on words like ctrl+f in jack?

**Comment by drewbrokke** [comment]
Thanks for letting me know about the typo :)

Unfortunately, no there is no search function yet.  It's a pretty significant effort to implement and I haven't been able to put in the time recently.  I'll definitely keep this issue open as a reference though - I'd love to have the feature too.

**Comment by BarbzYHOOL** [comment]
Ok thank you

**Comment by BarbzYHOOL** [comment]
Did you add it in the latest commits (titles)?

**Comment by drewbrokke** [comment]
I did.  I have not had time to prepare a release yet, but hopefully soon.  If you want to try this feature out now, you'll need to build from source.

**Comment by drewbrokke** [comment]
@BarbzYHOOL the new version of jack-cli has been released (1.0.0). It contains this feature.

See https://www.npmjs.com/package/jack-cli#searching for more info.

Please run npm i -g jack-cli to update. Thanks!
