### ISSUE TITLE
"[%SHA_SINGLE%]" not working

### ISSUE THREAD

**Issue by protoEvangelion** [drewbrokke/jack-cli#36]
With a fresh install of jack v0.2 I had to add spaces to `"[%SHA_SINGLE%]"` to get this to work:

```javascript
{
  "commands": [
    {
      "commandArray": ["git", "reset", "--soft", "[% SHA_SINGLE %]"],
      "description": "Soft Reset",
      "foreground": false,
      "key": "s"
    }
  ],
  "notificationTimeout": 5000
}
```

This works `"[% SHA_SINGLE %]"` though. Is that correct? Or should the docs just be updated?

**Comment by drewbrokke** [comment]
My apologies on the inconsistency. The correct documentation for the latest release is on NPM.  The README here on Github applies to the master branch.

**Comment by drewbrokke** [comment]
@protoEvangelion the new version of `jack-cli` (1.0.0) has been released, and `[%SHA_SINGLE%]` is now the correct token.
