### ISSUE TITLE
Open on GitHub

### ISSUE THREAD

**Issue by holatuwol** [drewbrokke/jack-cli#4]
If I hit some hotkey instead of hitting enter/space, it'd be great if the tool attempt to open whatever I've selected / whatever I'm viewing on GitHub instead of switching views.

**Comment by drewbrokke** [comment]
Would it make sense to default to origin or upstream?

**Comment by holatuwol** [comment]
I don't think it matters, as long as `git merge-base --is-ancestor COMMIT REMOTE_NAME/BRANCH_NAME` tells us that the commit we're looking at is on the remote.

Maybe iterate over all potential remotes with `git for-each-ref --format='%(refname)' refs/**/BRANCH_NAME`, and run the above command, but if the only thing that matches is `refs/heads/BRANCH_NAME`, just show an error message?

**Comment by natecavanaugh** [comment]
So, I have a bash script that does something similar, and perhaps it could be useful:
https://github.com/natecavanaugh/dotfiles/blob/4967b5de7f17313a95b2e5f3e48693467fc1f53c/bin/git-get-github-url

But the gist is that origin is the default remote, but can be specified by passing `-r REMOTE`, but it will also try to parse out the output of the `git remote -v` command and use that info to open the file.

But it also allows you to load a specific file, as well as load a compare view with something like
`git get-github-url HEAD^^..HEAD` will load up a view like this: https://github.com/natecavanaugh/dotfiles/compare/HEAD%5E%5E...HEAD

Anyways, just thought it might be useful depending on what you wanted to look at (and I could see some of these options used by using key modifiers when running the command).
:)

**Comment by drewbrokke** [comment]
Thanks @natecavanaugh.  I'll check that out (and maybe borrow it with your permission 👍 ).

**Comment by natecavanaugh** [comment]
@drewbrokke If there's anything in there worth taking, help yourself. I just use it whenever I need a link to a file I'm looking at on my system. I think your tool's a lot more useful :)

**Comment by drewbrokke** [comment]
Closing in favor of the solution for https://github.com/drewbrokke/jack-cli/issues/23.
https://github.com/drewbrokke/jack-cli#custom-key-commands
